(mc_deserialize_str): fix build due to C23 `strchr` prototype change
```
serialize.c: In function 'mc_deserialize_str':
serialize.c:155:18: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  155 |         semi_ptr = strchr (data + 1, SRLZ_DELIM_C);
      |                  ^
```

Signed-off-by: Yury V. Zaytsev <yury@shurup.com>