(vfs_path_from_str_deprecated_parser): fix build due to C23 `strchr` prototype change
```
path.c: In function 'vfs_path_from_str_deprecated_parser':
path.c:360:20: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  360 |         url_params = strchr (op, ':');  // skip VFS prefix
      |                    ^
```

Signed-off-by: Yury V. Zaytsev <yury@shurup.com>