(str_replace_all): fix build due to C23 `strchr` prototype change
```
replace.c: In function 'str_replace_all':
replace.c:69:27: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
   69 |     while ((needle_in_str = strstr (haystack, needle)) != NULL)
      |                           ^
```

Signed-off-by: Yury V. Zaytsev <yury@shurup.com>