(find_ignore_dir_search): fix build due to C23 `strstr` prototype change
```
find.c: In function 'find_ignore_dir_search':
find.c:1174:19: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 1174 |                 d = strstr (dir, *ignore_dir);
      |                   ^
```

Signed-off-by: Yury V. Zaytsev <yury@shurup.com>