(chdir_other_panel): fix build due to C23 `strrchr` prototype change
```
panel.c: In function 'chdir_other_panel':
panel.c:2976:20: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 2976 |         curr_entry = strrchr (vfs_path_get_last_path_str (panel->cwd_vpath), PATH_SEP);
      |                    ^
```

Signed-off-by: Yury V. Zaytsev <yury@shurup.com>